config/routes.rb
Rails.application.routes.draw do

  resources :poems
  root  "poems#index" 

end

app/models/poem.rb
class Poem < ActiveRecord::Base

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController

	def index

		@aux = Poem.all		 
		@poems = []

		@aux.each do |poem|
			@poems.push(poem) if poem.published
		end
		@poems
	end

	def show
		 @poems = Poem.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poetry</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/poems/index.html.erb
<h1>Here are my poems!</h1>

<% @poems.each do |poem| %>
  <h2><%= link_to(poem.title, poem_path(poem)) %></h2>
  <h3><%= poem.author %></h3>
<% end %>

app/views/poems/show.html.erb
<h1><%= @poems.title %></h1>
 
<%= simple_format(@poems.body) %>

<h3><%= @poems.author %></h3>

<%= link_to("Back to the list of poems", poems_path) %><br>